<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_home' => 'Home',
    'legal' => 'Legal',
    'page_my_account' => 'My Account',
    'page' => 'Page',
    'tomtom_header' => 'TomTom Header',
    'home_page' => 'home_page',
  ),
);


/* Auto generated by Themes Administration on : 2013.07.15 18:46:23 */
